name: setup_node
description: setup node.js

runs:
  using: composite
  steps:
  - uses: actions/cache@v2
    with:
      path: |
        node_modules
        */*/node_modules
      key: node_modules-${{ runner.os }}@220314-{{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        node_modules-${{ runner.os }}@220314-
  - uses: actions/setup-node@v2
    with:
      node-version: 16
  - shell: bash
    run: npm i -g pnpm
  - shell: bash
    run: pnpm i

